version: 2.1
orbs:
  node: circleci/node@4.7.0
workflows:
  run-tests:
    jobs:
      - node/run:
          pkg-manager: yarn
          yarn-run: build
      - node/test:
          pkg-manager: yarn
          run-command: test
          version: 14.17.5
